name: MML-mapserver

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: MML-mapserver
      run: docker build . --file Dockerfile --tag mapserver:$(date +%s)
